name: Setup Project
description: checks-out project, setup Node.js, and install packages
inputs:
  GITHUB_TOKEN:
    required: true
    description: "github token value"
  PAT_GITHUB:
    required: true
    description: "PAT for Github"
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Install Packages
      shell: bash
      run: |
        npm run install-1
        echo GITHUB_TOKEN ${{inputs.GITHUB_TOKEN}}
        echo PAT_GITHUB ${{inputs.PAT_GITHUB}}
    - name: Check Cache
      id: check_cache
      uses: actions/cache@v3
      with:
        path: ./
        key: set_up_key
    - name: Delete Cache
      env:
        GH_TOKEN: ${{inputs.PAT_GITHUB}}
      shell: bash
      if: steps.check_cache.outputs.cache-hit == 'true'
      run: gh cache delete set_up_key
    - name: Create Cache
      uses: actions/cache/save@v3
      with:
        path: ./
        key: set_up_key
    - name: List Cache
      env:
        GH_TOKEN: ${{inputs.GITHUB_TOKEN}}
      shell: bash
      run: gh cache list
