version: 2.1
jobs:
  ## has to be this name otherwise it will throw error: There are no workflows or build jobs in the config.
  build:
    docker:
      - image: cimg/node:19.7
    steps:
      - checkout
      - run:
          name: Install Packages
          working_directory: ./2-circle-ci
          command: npm install
      - run:
          name: Lint Fix
          working_directory: ./2-circle-ci
          command: npm run lint:fix
      - run:
          name: Lint Check
          working_directory: ./2-circle-ci
          command: npm run lint:check
      - run:
          name: Test
          working_directory: ./2-circle-ci
          command: npm run test
      - run:
          name: Build
          working_directory: ./2-circle-ci
          command: npm run build
  ## won't be detected, only job with name build gets detected by circle-ci
  ## solution is using workflows.
  publish:
    docker:
      - image: cimg/node:19.7
    steps:
      - run:
          name: Build
          working_directory: ./2-circle-ci
          command: npm run build
