# creates release tags after successful build for now.
name: CI-CD Github Actions Deploy Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  job-setup-project:
    env:
      NODE_VERSIONS: "[19.x, 20.x]"
      OS_TYPES: "[macos-latest, windows-latest]"
    strategy:
      matrix:
        node_version: [19.x, 20.x]
        os: [macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout using actions/checkout@v4
        uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
      - name: Install packages
        run: npm run install-1
      - name: WORKSPACE
        run: echo ${{github.workspace}}
      - name: Lint Fix
        working-directory: ./1-github
        run: |
          echo "${{ fromJSON(env.OS_TYPES) }}"
          npm run lint:fix
      - name: Lint Check
        run: npm run lint:check
        working-directory: ./1-github
      - name: Go To 1-github directory
        run: echo "deploy"
    # uses: ./.github/workflows/setup.yml
    # with:
    #   node_version: ${{matrix.node_version}}
    #   os: ${{matrix.os}}
  #   job-build-project:
  #     strategy:
  #       matrix:
  #         node_version: [19.x, 20.x]
  #         os: [macos-latest, windows-latest]
  #     needs: job-setup-project
  #     uses: ./.github/workflows/build.yml
  #     with:
  #       node_version: ${{matrix.node_version}}
  #       os: ${{matrix.os}}
#   job-deploy-project:
#     strategy:
#       matrix:
#         node_version: [19.x, 20.x]
#         os: [macos-latest, windows-latest]
#     needs: job-setup-project
#     runs-on: ${{matrix.os}}
#     steps:
#       - name: WORKSPACE
#         run: echo ${{github.workspace}}
#       - name: Go To 1-github
#         run: cd './1-github'
#       - name: WORKSPACE
#         run: echo ${{github.workspace}}
#       - name: Lint Fix
#         run: npm run lint:fix
#       - name: Lint Check
#         run: npm run lint:check
#       - name: Go To 1-github directory
#         run: echo "deploy"
