# creates release tags after successful build for now.
name: Publish
on:
  workflow_dispatch:
jobs:
  job-build:
    uses: "./.github/workflows/verify.yml"
  job-release:
    needs: job-build
    runs-on: macos-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: set_up
        with:
          path: ./
          key: set_up_key
      # - name: Build
      #   uses: "./.github/actions/build/"
      - name: Publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
