# creates release tags after successful build for now.
name: Publish
on:
  workflow_dispatch:
jobs:
  job-build:
    env:
      NODE_VERSIONS: "[19.x, 20.x]"
      OS_TYPES: "[macos-latest, windows-latest]"
    strategy:
      matrix:
        node_version: [19.x, 20.x]
        os: [macos-latest, windows-latest] ## not using env.OS_TYPES as env context is not available at job level.
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: "./.github/actions/setup/"
      - name: Build
        uses: "./.github/actions/build/"
  job-release:
    needs: job-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: "./.github/actions/setup/"
      - name: Build
        uses: "./.github/actions/build/"
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
