#  setup build environment for the project
name: CI-CD Github Actions Setup
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      node_version:
        type: string
        required: true
jobs:
  set-up:
    runs-on: ${{inputs.os}}
    steps:
      - name: Use Node.js version ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node_version}}
      - name: Install packages
        run: npm run install-1
