#  setup build environment for the project
name: CI-CD Github Actions Setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  set_up:
    strategy:
      matrix:
        node_version: [16.x, 19.x, 20.x]
    runs-on: [macos-latest, windows-latest]
    steps:
      - name: Checkout using actions/checkout@v4
        uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
      - name: Install packages
        run: npm install
