# Builds everytime code is merged in main branch
name: Verify Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  job-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: "./.github/actions/setup/"
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  job-build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: job-setup
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          ls -l -a
      - name: Restore Cache
        uses: actions/cache/restore@v3
        id: set_up
        with:
          path: /
          key: set_up_key
      - name: Install Dependencies
        if: steps.set_up.outputs.cache-hit != 'true'
        run: echo cache missed fresh install
      - name: List
        run: |
          ls -l -a
      - name: Build
        uses: "./.github/actions/build/"
