# Builds everytime code is merged in main branch
name: Verify Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:
jobs:
  job-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: "./.github/actions/setup/"
  job-build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: job-setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: "./.github/actions/build/"
